version: '3'

services:
  app:
    container_name: rest_api
    build: .
    ports:
      - 80:80
    networks:
      - default
    volumes:
      - .:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: helloworld
      MYSQL_DB: jwt_db
    networks:
      - local
    depends_on:
      - mysql

  mysql:
    container_name: rest_db
    image: mysql:8.0.17
    volumes:
      - jwt-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: jwt_db
    ports:
      - "3308:3306"
    expose:
      - '3308'
    networks:
      - local
networks:
  local:
    driver: bridge
volumes:
  jwt-mysql-data: